const EASY_MODE = {
  label: "Easy",
  fixedBet: 10,
  symbols: [
    {
      id: "ten",
      icon: "10",
      image: "assets/icons/number-10.png",
      weight: 19,
      minCount: 7,
      baseMultiplier: 0.024,
      extraMultiplier: 0.007,
    },
    {
      id: "queen",
      icon: "Q",
      image: "assets/icons/letter-q.png",
      weight: 17,
      minCount: 7,
      baseMultiplier: 0.036,
      extraMultiplier: 0.01,
    },
    {
      id: "king",
      icon: "K",
      image: "assets/icons/letter-k.png",
      weight: 15,
      minCount: 7,
      baseMultiplier: 0.05,
      extraMultiplier: 0.013,
    },
    {
      id: "ace",
      icon: "A",
      image: "assets/icons/letter-a.png",
      weight: 13,
      minCount: 7,
      baseMultiplier: 0.07,
      extraMultiplier: 0.017,
    },
    {
      id: "anchor",
      icon: "Anc",
      image: "assets/icons/anchor.png",
      weight: 12,
      minCount: 7,
      baseMultiplier: 0.11,
      extraMultiplier: 0.026,
    },
    {
      id: "cannon",
      icon: "Can",
      image: "assets/icons/cannon.png",
      weight: 10,
      minCount: 7,
      baseMultiplier: 0.2,
      extraMultiplier: 0.043,
    },
    {
      id: "skull-coin",
      icon: "Skull",
      image: "assets/icons/skull-coin.png",
      weight: 8,
      minCount: 7,
      baseMultiplier: 0.36,
      extraMultiplier: 0.072,
    },
  ],
};

const HARD_MODE = {
  label: "Hard",
  fixedBet: 100,
  symbols: [
    {
      id: "ten",
      icon: "10",
      image: "assets/icons/number-10.png",
      weight: 26,
      minCount: 8,
      baseMultiplier: 0.111,
      extraMultiplier: 0.025,
    },
    {
      id: "queen",
      icon: "Q",
      image: "assets/icons/letter-q.png",
      weight: 20,
      minCount: 8,
      baseMultiplier: 0.171,
      extraMultiplier: 0.038,
    },
    {
      id: "king",
      icon: "K",
      image: "assets/icons/letter-k.png",
      weight: 15,
      minCount: 8,
      baseMultiplier: 0.262,
      extraMultiplier: 0.056,
    },
    {
      id: "ace",
      icon: "A",
      image: "assets/icons/letter-a.png",
      weight: 11,
      minCount: 8,
      baseMultiplier: 0.393,
      extraMultiplier: 0.081,
    },
    {
      id: "anchor",
      icon: "Anc",
      image: "assets/icons/anchor.png",
      weight: 8,
      minCount: 9,
      baseMultiplier: 0.681,
      extraMultiplier: 0.131,
    },
    {
      id: "cannon",
      icon: "Can",
      image: "assets/icons/cannon.png",
      weight: 5,
      minCount: 9,
      baseMultiplier: 1.21,
      extraMultiplier: 0.242,
    },
    {
      id: "skull-coin",
      icon: "Skull",
      image: "assets/icons/skull-coin.png",
      weight: 3,
      minCount: 10,
      baseMultiplier: 2.772,
      extraMultiplier: 0.554,
    },
  ],
};

const GAME_CONFIG = {
  initialBalance: 300,
  defaultMode: "easy",
  columnCount: 6,
  rowCount: 5,
  modes: {
    easy: EASY_MODE,
    hard: HARD_MODE,
  },
  spinDurationMs: 900,
  animationTickMs: 120,
  winFlashMs: 650,
  clearDelayMs: 260,
  tumbleDropMs: 420,
  cascadePauseMs: 240,
};

window.GAME_CONFIG = GAME_CONFIG;



