const GAME_CONFIG = {
  initialBalance: 100,
  fixedBet: 10,
  columnCount: 6,
  rowCount: 5,
  symbols: [
    {
      id: "ten",
      icon: "10",
      image: "assets/icons/number-10.png",
      weight: 19,
      minCount: 7,
      baseMultiplier: 0.024,
      extraMultiplier: 0.007,
    },
    {
      id: "queen",
      icon: "Q",
      image: "assets/icons/letter-q.png",
      weight: 17,
      minCount: 7,
      baseMultiplier: 0.036,
      extraMultiplier: 0.01,
    },
    {
      id: "king",
      icon: "K",
      image: "assets/icons/letter-k.png",
      weight: 15,
      minCount: 7,
      baseMultiplier: 0.05,
      extraMultiplier: 0.013,
    },
    {
      id: "ace",
      icon: "A",
      image: "assets/icons/letter-a.png",
      weight: 13,
      minCount: 7,
      baseMultiplier: 0.07,
      extraMultiplier: 0.017,
    },
    {
      id: "anchor",
      icon: "⚓",
      image: "assets/icons/anchor.png",
      weight: 12,
      minCount: 7,
      baseMultiplier: 0.11,
      extraMultiplier: 0.026,
    },
    {
      id: "cannon",
      icon: "💣",
      image: "assets/icons/cannon.png",
      weight: 10,
      minCount: 7,
      baseMultiplier: 0.2,
      extraMultiplier: 0.043,
    },
    {
      id: "skull-coin",
      icon: "☠️",
      image: "assets/icons/skull-coin.png",
      weight: 8,
      minCount: 7,
      baseMultiplier: 0.36,
      extraMultiplier: 0.072,
    },
  ],
  spinDurationMs: 900,
  animationTickMs: 120,
  winFlashMs: 650,
  clearDelayMs: 260,
  tumbleDropMs: 420,
  cascadePauseMs: 240,
};

window.GAME_CONFIG = GAME_CONFIG;
